name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download artifact - libglibutil
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: clearfraction/libglibutil
          workflow: build-core.yml
          check_artifacts: true
      - name: Download artifact - libgbinder
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: clearfraction/libgbinder
          workflow: build.yml
          check_artifacts: true
      - name: Download artifact - gbinder-python
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: clearfraction/gbinder-python
          workflow: build.yml
          check_artifacts: true
      - name: Download artifact - pyclip
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: clearfraction/pyclip
          workflow: build-core.yml
          check_artifacts: true
      - name: Download artifact - lxc
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: clearfraction/lxc
          workflow: build.yml
          check_artifacts: true          
      - name: Building a package
        run: |
          curl -LO https://raw.githubusercontent.com/clearfraction/tools/master/build-core.sh && chmod +x build-core.sh
          docker run --privileged --cap-add=SYS_ADMIN --security-opt apparmor:unconfined -v $(pwd):/home clearlinux:latest sh -c "cd /home && ./build-core.sh"
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          path: RPMS/*.rpm
      - name: Extract artifacts
        run:  mkdir /tmp/waydroid-bundle && for rpm in RPMS/*.rpm artifact/*rpm; do echo "$rpm"; rpm2cpio "$rpm" | cpio -D /tmp/waydroid-bundle -idm; done
      - name: Upload Waydroid artifacts
        uses: actions/upload-artifact@v2
        with:
          name: waydroid-bundle
          path: /tmp/waydroid-bundle
